name: Translate Text with Azure OpenAI
on: [workflow_dispatch]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Process Text with Azure OpenAI
        id: process-text
        uses: yuichielectric/azure-openai-action@main
        with:
          api_url: ${{ secrets.API_URL }}
          deployment_id: ${{ secrets.DEPLOYMENT_ID }}
          api_key: ${{ secrets.API_KEY }}
          system_prompt: 'Translate the text into Japanese.'
          input_text: 'Hello, how are you?'

      - name: Print the Response
        run: echo "${{ steps.process-text.outputs.response }}"
